SELECT * FROM employees ORDER BY FIRST_NAME ASC;
SELECT FIRST_NAME, LAST_NAME, SALARY, SALARY*.15 PF from employees;
SELECT SUM(SALARY) FROM employees;
SELECT FIRST_NAME,LAST_NAME,MAX(SALARY) FROM employees;
SELECT FIRST_NAME,LAST_NAME,MIN(SALARY) FROM employees;
SELECT AVG(SALARY) FROM employees;
SELECT COUNT(FIRST_NAME) FROM employees;
